### ISSUE TITLE
Do you have solutions for the wireshark lab v8.1?

### ISSUE THREAD

**Issue by 1475505** [Ye-zixiao/Computer_Networking-A-Top-Down-Approach-#1]
Could u please share the solutions for the wireshark lab v8.1? I'm also learning it and needing a reference solution.

**Comment by Ye-zixiao** [comment]
Sorry, I don't have the resources you want.

**Comment by Ye-zixiao** [comment]
> Could u please share the solutions for the wireshark lab v8.1? I'm also learning it and needing a reference solution.
Sorry, I don't have the resources you want.
